Documentation:
  Enabled: false
HashSyntax:
  EnforcedStyle: hash_rockets
LineLength:
  Max: 200
MethodLength:
  Max: 50
RegexpLiteral:
  MaxSlashes: 0
RescueModifier:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
