language: ruby
cache: bundler
bundler_args: "--without kitchen_vagrant"
rvm:
- 2.1.2
before_install:
- echo -n $AWS_KEY_CHUNK_{0..30} >> ~/.ssh/ci.pem.base64
- cat ~/.ssh/ci.pem.base64 | tr -d ' ' | base64 --decode > ~/.ssh/ci.pem
after_script:
- bundle exec kitchen destroy
before_deploy:
- bundle exec berks package cookbook-opentsdb.tar.gz
env:
  global:
  - KITCHEN_LOCAL_YAML="$TRAVIS_BUILD_DIR/.kitchen.cloud.yml"
  - secure: JOXAcHNpCeE5w3VMdtNxrrnmWIDUUdbhe1oTyZA4D7z+oIkJvgBQdnnQUXfjQbUc+zX4RL7bxXdGpBiNGN4WyGE9UEIQqSrjfBYgKZ8ml7UT1+IbFppco5UnZNMNMWx6qEhmSvWCo7hkmJ2462sFZ8S4C0fzcEFkhumEPVmNqQk=
  - secure: TEY0284lebCzQbBm2qmuFJ4G1yM9ZyJY7CAZnhc+nwCiWuhMX2nsVQpuYHBYgUhD/QBarLaBmuqPjxigXX1F5vtB4CYbgresXFNDMOSxvSQo+MvvLzpHKTDr14xAVbuZlKyMX8sbtRg2z1YiY22PFpNpIbqsSeH9UI72+xgi92s=
  - secure: NXR7/zF042uD5VVqkzpSZCxwdIpJADP0z4pFgPiE0xz31AKUJV2zdda8YuWwlT9+xrr51JRUmtlA4h84UKjSHhqY00w2giX3BL37CGFM8YF1k2NpfQNtZmjTZYCD4IieTeQhRiLOQr1A9boWG9Y5sN2Kas/qBEwVaHE8X0g53QI=
  - secure: hiJ98Asoi7OasPMxSCnwYPDhSif0SRPJDWuuE34M0Zk5MEuGUosf0aNC74AOAdIhvEkwZi40RUY9m2PlYYzDZV8L8RNooWJOVh/t0abY4H2aWFzVvGLCkIkx2oLfE0S2vUQY0nV1Q5YO9WU0Gg585dch0S3+jASckYcOGR3KmT0=
  - secure: AYeeApdXUzaTpUb0c/E4RzEVs8mWt9qbq6ZEY86uhPpc6CXQrlg9iguPOd9sfFo6zxFnNGNehr5l9rVMrCGINfGpUFJ4AP2GJHADuz3otLzg5xcKeSCePNp1cKkxPi8hb72lwOjQCVhhxtO3Cot35U709sK6aHXqpZ4g8ur7bFo=
  - secure: M5/WiMlyBWyh8xuxvbyt5tAAkepn6Mg/deJeZzJmCODW7zs76SSK1Xa7k/ZHH5OfUWsF+S2l6hNi7thUHA84gmsKgji/LIP+pnlB7pVdIVHBKUL2MEBHizxbnIzKvuJPgM+t/stPZlZZq+F/oS5lEAHetd9ifCbkcHNg1Za3/Jk=
  - secure: W9laqhex+wty/tcnErqalDDa2VOwpMPOF2k6AG8V1N8jB+yOMmgnkjmVV7cylm4DcOAM8j6LECNT8hQQJL7bbB0nI2iAjv6+kFnIu+CHv5GZ+ZgteaqL4kkkR+2VGY8f6lgDjgNjQypXf3ToMvVbXPnZRBFIZNlGJlihO/TDjtc=
  - secure: Ve/oaKCj1sf1q4e9geG+eqbAC0bnHEQINxL9WmsPBtylygX5hJOX03DYDQYS8QvHW054SGOrPnFKlCKA24E5/mgeG3I+dLzTPLH9xC2NbVHc1Pejnx5EDA47Q8ZFh9QRTarwMuNTwCcN7n9Vxy9u7iCBlt/fjd46cV/j/vjX+IE=
  - secure: E5DGI5DBmAX5VukTqHeFpOSUToEQFcd64IfsIaMYaqLIyB0ArLqZ2CpdyK+wtLU0BOBI5WjzB+Dzwc524H9VrMRi50jE37FAfYJ8Nq0RRiJq+jSX11qQkxmZcllSNUkjEOuwuTPt5OGK/AeCHapn7m5ufsw2+USo2cy5qUAN1Ks=
  - secure: diiOpf+FqI5UwEOEjUcYGPmQCy8P6CFu/GD7tDo34gnKAL/Hflu8akQwzR5+OL9TJp/1SUduD2jWhU5SF3+A6ttPNihamNkyS0ccicU3hlpMDIyrPzYcavLvacnY4pl3AUMY6pvB9ibSNMtJd8a1anKAekDfTQchhqHoAlepYfo=
  - secure: Gho0dkK78tEw4mdgLW6mwqPhgQ8dx9K8Xc0/7nC/9+yr4axlbg0Qjkz/42ruMw+tdF6tPmfFRzTFiBriZoRuxJ3bIr5jBQIv96fNFHLRZ9ApoiyPSvUk++KFwkM3jXqcApOetxK9/pW3vCzHsYfjgBoGyhGfxAnjlyIqfgSgGac=
  - secure: HVu0iVeCLi1ymdQBWjqSm+UBIetauEtwUvwnIs1Y7GUEa8hNGxufushxOuaYNSXJg6hEfYuYu2VmbU4WmRc68nkcR6xKVzdgvgHs+EXDi3x/1gXdeFlN75goeL0IK/kyIDFqEmYhIJgBYMqYMFTvUr/AXPjySIwxzDLuiloFA5s=
  - secure: cswawPAmoQpDvBH/X1pyRmZAPiHBpDiR2LVrmsvMjJhhClXnNcL0e1w2KzMi8LccX1GupNJQAFqk2EKALPKK45a6hHGNjy39KIZcRr+XYDKZ3pkE1ICCo0/t+y+XwJbEsz/9piSC05rylaJ5UDhtJQYJQF0YU5mzgl0HpC469jw=
  - secure: VLPI8C9DSLuxZjP9e6zAdqqgt78EipPldHAXzGoTTYkWfxuE9YPJsYZ2R871OBFoNjUiY1Me7heRmZR79fMbjLaWCoch/WfMvIfm3KUA4WbqCHWyqbkuMUYie+jxzPnkPC6raHmHz1XMI+7RyLc3Oi8G7XfM8Y5dtdABt540m7Q=
  - secure: JJeUzE4/8jIiPOm1Foqal13zm0TnTB0r85enPYCOg8z31PloctVAtz8CGaQV4EjvVPBMJEZTZ6azd43gkAHIvjVAPk66rifN7tPJiCUp834aF605r0VVHCWwxwla1dM0CV6wNoeTwfjQ4Tihl68+JbyInnsrbBmN3dY40VdrvHs=
  - secure: eTDGXzh6xDIP0yP+vb7s9NrHe5OKbfhOhl7yXtZkA88CsJis/F8kuDe5XB2CFZJ/rcgJFnX64ELfWlJA5fomwQDNrMDCmSy49RRj3do5YwUza1Urt9YIRh0PKVR6md4lbE+Vzl+BZ9wZbEWVzwjFm8CJ/Uo0a4eqetSpaaYjrWs=
  - secure: ceTjwhN9e0p8PWsZ5ywxXE4yXS36PFQnPMuJjAJvZOpQhdR0whTaDt8btmok/rcSyeVCoHGF4GpAoSo0A2AT8gezhv5jTDCQ5TPZw0H0S1c4ZYylRYEJ3/0ZjGex34eEjyTS1tLrsPHiMdVF+S6EudPQUbnSG9/SaOhX7kLIn7w=
  - secure: I7PnyP2tTtmz0sJmilGVBqxmITHWqZExRaZhFyVZ5+3uIY7rPLrUSTuNMCJxJqJq+AV2J/2o+d+XHUp6PoOf+eeGoZlXmtwZGWaAVrtICYy1vkJHOLYO1phIAWc4EEoH+9MFDsoCjAfrcemEuxfQ/qwsI8DBwbgOU3fg7vukj+4=
  - secure: WoJU3BnoiKZbcjBFvcEnTaEf9hGsMNNHr6Kt+2yRHh8aBAfsjhBuQdpUVh3EXPP/VXKqbnL67GzJ5saWO8+VinE8+YHvjlw6F+Bck7FX0zEu8XJyK3MLVlrdSiowEXBjmBSOxpErk1OJDwPtNt0lOGxLHrDFDxbcCkuLidUY2bw=
  - secure: WbrYEZZTOZhVlAK/Thn9MjSd8Pyqd1C0V9X9G1WllVf+9GCokhetvWza+ivb/S5ipIRcZvVTdqJr4ZZSeBiNW3JFVmaIqEVbUGm0+2EnNuI6ihfWnuHiu8EybZL5TU69qp00XrhQZokDWEiSIZ9ul1wW6PtLUphzwq4yCgF0c/I=
  - secure: bzc1nyL64fyXo389L0ZHOZ7XKaaLfkLyp+mrtxU08KbEFOJwXRPcEOGMB4FW5CGj6Fc1PtEiVL6gQYv1/sv/jWWepN7usTIU2IMxh8d8FSI9Co4Wh45aR5agwxFn9Ccuw+XlqyZ73pNUd6P8R/9Oema8/NJx85dH7BhG2xfZx4c=
  - secure: KiVSvh5ukPqmJDCpzTG9VHvPyR8qE5jZb7Gpc4+7LLoWXWxky1FYWYK/51jfJrs/4wSIcpD60AsnMmWOd+4cHAOQCW/fVkt6XEKfkw4Ec1SlWQBLbAw/fqgDwuEriaBrR1m39z+u6dABceGBHrzmBzS/g5aqotbgkGtfLu4sR3w=
  - secure: YbdE+TldVmGAhFC5l2I5kfN9XV46sIDTzkEktgqmRpQSkPXs/+/zyg4lNkgI2xTnT7Glsi9ejdIXN90jlqDeB41M59i8/GET/Hf300x+hIafaaLDZFEz203LN8rzyEqRJO9YHx372KGICoeO4qtQhnNrKmTzNrFVO7wB9j6cpQc=
  - secure: f1ybpD+bbcyc2IfMew1BhvjQNJaxXsG7S5uVhtwtJRcII24ljOnbEd3ekhNHT7YOzGdKEm3Q4gbg9fTYc5/WP63yNGkfU1I9sgsaFr7fO7PWA417TX7t/jK4MrZWJGAurcwJfE4hsw0ZCgM19CJQNwjc6rwICJIgWSu1TVe68wo=
  - secure: BPOAP0TUJsMdlvgiaGJ3XL4oIMkyOYXXwKpyQO3PLd7UsogMTHooOI70KPwfWtz/2qIjijsPFNZUEHuX3eHtwjz+OgO0kwaZJneYWeK+oSmtyYd+JPob+PPc5Wz9s1ShaAtyCHAP0kEfD6wmW4Rjq9zj9+LubiopQ4Uh5sM0jlk=
  - secure: iC36uR5UGNDaiBRpnv1gn3xsYalPZcHJg9L9Fu/mgIPYH7W4YcJmEIefEg8MkjPD+fscFGQ+Xg5JGq3NDp8800D5x0NNxrjIZd4yvE6VNddEL7nBlForIIUVpOfHL8zp3pf52TlQpzHnIJ9IeJOJAPeEKdw+eL7/tNE9LUnkKLI=
  - secure: dZwYPxFVWQkps2Bc67cvEzkE6ZXFkGkqDUhGFds3+R/EbiNqJgfigQndT0KQVO+ND4MXyRVNhcDhqfoMNwiXXRyfh/F4gXmcjgENZwaQxLtrLWJT+dmZMEyaZh400FfOqRQ5waa7R2TWJ2+x6aY1l5LSTjkS4Ffpw+qUTqmwaSI=
  - secure: MnqnHDOMsxmQqdMdJt3FNf7dYo5dKQX0NDyyusfGM6ViXNMwMWZOGVYkqmp910AcLEQJIyR8n1DQhHexS9oWbImkgNdEAdX1afivrMaS2TFrGu3PPOJR7X0wmA3iZY7slsPRb3i4bSgWjewQa9Yui2tKF1KAll4Vw6tmrZii6Ug=
deploy:
  provider: releases
  api_key:
    secure: HlZJoFlIaKmubYkMWvYEsRtIiAKCPm3Wf0h/ERmZopV/B5nwLqThR5g7eYlr81Y6ATW3dl4zy7emmriLh/duzFpyq1E0HCdGdYOdH7vAlJf8o953gtpGy9ZBG7CTObwdrXojUFG12s1ousiA7wsAMyAYBfJZ1fmYNkGwxfl/Cjo=
  file: cookbook-opentsdb.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: WhoopInc/cookbook-opentsdb
